Repository amdla/PZ-backend, pull requests merged in 2025-03, with the labels that each got.

#8 KAN-14
  api/models.py
  api/serializers.py
Labels: documentation

#9 Dodanie w modelu informacji o zmianie pokoju
  api/database-structure.dbml
  api/models.py
  api/serializers.py
Labels: enhancement

#10 Merge pull request #9 from amdla/KAN-12
  api/views.py
  config/urls.py
Labels: enhancement

#13 KAN-39-Create-Postman-tests-for-User-endpoints
  README.md
  postman_test/PZ Collection.postman_collection.json
  postman_test/PZ Environment.postman_environment.json
Labels: enhancement, test
